/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Guardable, GuardableInterface } from "../Guardable";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousGuardian",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newGuardian",
        type: "address",
      },
    ],
    name: "GuardianPulled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousGuardian",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newGuardian",
        type: "address",
      },
    ],
    name: "GuardianPushed",
    type: "event",
  },
  {
    inputs: [],
    name: "guardian",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pullGuardian",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newGuardian_",
        type: "address",
      },
    ],
    name: "pushGuardian",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceGuardian",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50600080546001600160a01b03191633178082556040516001600160a01b039190911691907f0960fb9900fb8096216606c4f7fc2fce5d08cc0c82da55cec8619b66b5238481908290a361032c806100696000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c8063452a932014610051578063a987f55a14610075578063be11f1dd1461009d578063e9946f6c146100a5575b600080fd5b6100596100ad565b604080516001600160a01b039092168252519081900360200190f35b61009b6004803603602081101561008b57600080fd5b50356001600160a01b03166100bc565b005b61009b61016d565b61009b610227565b6000546001600160a01b031690565b6000546001600160a01b031633146101055760405162461bcd60e51b81526004018080602001828103825260258152602001806102d46025913960400191505060405180910390fd5b600080546040516001600160a01b03808516939216917f1319a4636487e78c9c7018006e23fb80010cef0c7a0588a5b4612ca630b429aa91a36001805473ffffffffffffffffffffffffffffffffffffffff19166001600160a01b0392909216919091179055565b6001546001600160a01b031633146101b65760405162461bcd60e51b81526004018080602001828103825260278152602001806102f96027913960400191505060405180910390fd5b600154600080546040516001600160a01b0393841693909116917f0960fb9900fb8096216606c4f7fc2fce5d08cc0c82da55cec8619b66b523848191a3600180546000805473ffffffffffffffffffffffffffffffffffffffff199081166001600160a01b03841617909155169055565b6000546001600160a01b031633146102705760405162461bcd60e51b81526004018080602001828103825260258152602001806102d46025913960400191505060405180910390fd5b600080546040516001600160a01b03909116907f0960fb9900fb8096216606c4f7fc2fce5d08cc0c82da55cec8619b66b5238481908390a36000805473ffffffffffffffffffffffffffffffffffffffff1990811690915560018054909116905556fe477561726461626c653a2063616c6c6572206973206e6f742074686520677561726469616e477561726461626c653a206d757374206265206e657720677561726469616e20746f2070756c6ca164736f6c6343000705000a";

export class Guardable__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Guardable> {
    return super.deploy(overrides || {}) as Promise<Guardable>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Guardable {
    return super.attach(address) as Guardable;
  }
  connect(signer: Signer): Guardable__factory {
    return super.connect(signer) as Guardable__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GuardableInterface {
    return new utils.Interface(_abi) as GuardableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Guardable {
    return new Contract(address, _abi, signerOrProvider) as Guardable;
  }
}
