/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IGuardable, IGuardableInterface } from "../IGuardable";

const _abi = [
  {
    inputs: [],
    name: "guardian",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pullGuardian",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newGuardian_",
        type: "address",
      },
    ],
    name: "pushGuardian",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceGuardian",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IGuardable__factory {
  static readonly abi = _abi;
  static createInterface(): IGuardableInterface {
    return new utils.Interface(_abi) as IGuardableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGuardable {
    return new Contract(address, _abi, signerOrProvider) as IGuardable;
  }
}
