/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IsOHMOLD, IsOHMOLDInterface } from "../IsOHMOLD";

const _abi = [
  {
    inputs: [],
    name: "INDEX",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IsOHMOLD__factory {
  static readonly abi = _abi;
  static createInterface(): IsOHMOLDInterface {
    return new utils.Interface(_abi) as IsOHMOLDInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IsOHMOLD {
    return new Contract(address, _abi, signerOrProvider) as IsOHMOLD;
  }
}
