/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IStakingV1, IStakingV1Interface } from "../IStakingV1";

const _abi = [
  {
    inputs: [],
    name: "index",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "_trigger",
        type: "bool",
      },
    ],
    name: "unstake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IStakingV1__factory {
  static readonly abi = _abi;
  static createInterface(): IStakingV1Interface {
    return new utils.Interface(_abi) as IStakingV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStakingV1 {
    return new Contract(address, _abi, signerOrProvider) as IStakingV1;
  }
}
