/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { SOHMInterface, SOHMInterfaceInterface } from "../SOHMInterface";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "circulatingSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class SOHMInterface__factory {
  static readonly abi = _abi;
  static createInterface(): SOHMInterfaceInterface {
    return new utils.Interface(_abi) as SOHMInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SOHMInterface {
    return new Contract(address, _abi, signerOrProvider) as SOHMInterface;
  }
}
