/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface BondTellerInterface extends ethers.utils.Interface {
  functions: {
    "FERs(address)": FunctionFragment;
    "authority()": FunctionFragment;
    "bonderInfo(address,uint256)": FunctionFragment;
    "feReward()": FunctionFragment;
    "getReward()": FunctionFragment;
    "indexesFor(address,uint256)": FunctionFragment;
    "newBond(address,address,uint256,uint256,uint256,address)": FunctionFragment;
    "pendingFor(address,uint256)": FunctionFragment;
    "pendingForIndexes(address,uint256[])": FunctionFragment;
    "percentVestedFor(address,uint256)": FunctionFragment;
    "redeem(address,uint256[])": FunctionFragment;
    "redeemAll(address)": FunctionFragment;
    "setAuthority(address)": FunctionFragment;
    "setFEReward(uint256)": FunctionFragment;
    "totalPendingFor(address)": FunctionFragment;
    "updateIndexesFor(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "FERs", values: [string]): string;
  encodeFunctionData(functionFragment: "authority", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "bonderInfo",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "feReward", values?: undefined): string;
  encodeFunctionData(functionFragment: "getReward", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "indexesFor",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "newBond",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingFor",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingForIndexes",
    values: [string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "percentVestedFor",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [string, BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "redeemAll", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setAuthority",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setFEReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPendingFor",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateIndexesFor",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "FERs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "authority", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bonderInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feReward", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getReward", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "indexesFor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "newBond", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendingFor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingForIndexes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "percentVestedFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "redeemAll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFEReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPendingFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateIndexesFor",
    data: BytesLike
  ): Result;

  events: {
    "AuthorityUpdated(address)": EventFragment;
    "BondCreated(address,uint256,uint256)": EventFragment;
    "Redeemed(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AuthorityUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BondCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Redeemed"): EventFragment;
}

export type AuthorityUpdatedEvent = TypedEvent<
  [string] & { authority: string }
>;

export type BondCreatedEvent = TypedEvent<
  [string, BigNumber, BigNumber] & {
    bonder: string;
    payout: BigNumber;
    expires: BigNumber;
  }
>;

export type RedeemedEvent = TypedEvent<
  [string, BigNumber] & { bonder: string; payout: BigNumber }
>;

export class BondTeller extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: BondTellerInterface;

  functions: {
    FERs(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    authority(overrides?: CallOverrides): Promise<[string]>;

    bonderInfo(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        principal: string;
        principalPaid: BigNumber;
        payout: BigNumber;
        vested: BigNumber;
        created: BigNumber;
        redeemed: BigNumber;
      }
    >;

    feReward(overrides?: CallOverrides): Promise<[BigNumber]>;

    getReward(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    indexesFor(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    newBond(
      _bonder: string,
      _principal: string,
      _principalPaid: BigNumberish,
      _payout: BigNumberish,
      _expires: BigNumberish,
      _feo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pendingFor(
      _bonder: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    pendingForIndexes(
      _bonder: string,
      _indexes: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { pending_: BigNumber }>;

    percentVestedFor(
      _bonder: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { percentVested_: BigNumber }>;

    redeem(
      _bonder: string,
      _indexes: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    redeemAll(
      _bonder: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAuthority(
      _newAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFEReward(
      reward: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totalPendingFor(
      _bonder: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { pending_: BigNumber }>;

    updateIndexesFor(
      _bonder: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  FERs(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  authority(overrides?: CallOverrides): Promise<string>;

  bonderInfo(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      principal: string;
      principalPaid: BigNumber;
      payout: BigNumber;
      vested: BigNumber;
      created: BigNumber;
      redeemed: BigNumber;
    }
  >;

  feReward(overrides?: CallOverrides): Promise<BigNumber>;

  getReward(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  indexesFor(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  newBond(
    _bonder: string,
    _principal: string,
    _principalPaid: BigNumberish,
    _payout: BigNumberish,
    _expires: BigNumberish,
    _feo: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pendingFor(
    _bonder: string,
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  pendingForIndexes(
    _bonder: string,
    _indexes: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  percentVestedFor(
    _bonder: string,
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  redeem(
    _bonder: string,
    _indexes: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  redeemAll(
    _bonder: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAuthority(
    _newAuthority: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFEReward(
    reward: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totalPendingFor(
    _bonder: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  updateIndexesFor(
    _bonder: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    FERs(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    authority(overrides?: CallOverrides): Promise<string>;

    bonderInfo(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        principal: string;
        principalPaid: BigNumber;
        payout: BigNumber;
        vested: BigNumber;
        created: BigNumber;
        redeemed: BigNumber;
      }
    >;

    feReward(overrides?: CallOverrides): Promise<BigNumber>;

    getReward(overrides?: CallOverrides): Promise<void>;

    indexesFor(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    newBond(
      _bonder: string,
      _principal: string,
      _principalPaid: BigNumberish,
      _payout: BigNumberish,
      _expires: BigNumberish,
      _feo: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingFor(
      _bonder: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingForIndexes(
      _bonder: string,
      _indexes: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    percentVestedFor(
      _bonder: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    redeem(
      _bonder: string,
      _indexes: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    redeemAll(_bonder: string, overrides?: CallOverrides): Promise<BigNumber>;

    setAuthority(
      _newAuthority: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setFEReward(reward: BigNumberish, overrides?: CallOverrides): Promise<void>;

    totalPendingFor(
      _bonder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateIndexesFor(_bonder: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "AuthorityUpdated(address)"(
      authority?: string | null
    ): TypedEventFilter<[string], { authority: string }>;

    AuthorityUpdated(
      authority?: string | null
    ): TypedEventFilter<[string], { authority: string }>;

    "BondCreated(address,uint256,uint256)"(
      bonder?: string | null,
      payout?: null,
      expires?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { bonder: string; payout: BigNumber; expires: BigNumber }
    >;

    BondCreated(
      bonder?: string | null,
      payout?: null,
      expires?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { bonder: string; payout: BigNumber; expires: BigNumber }
    >;

    "Redeemed(address,uint256)"(
      bonder?: string | null,
      payout?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { bonder: string; payout: BigNumber }
    >;

    Redeemed(
      bonder?: string | null,
      payout?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { bonder: string; payout: BigNumber }
    >;
  };

  estimateGas: {
    FERs(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    authority(overrides?: CallOverrides): Promise<BigNumber>;

    bonderInfo(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    feReward(overrides?: CallOverrides): Promise<BigNumber>;

    getReward(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    indexesFor(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    newBond(
      _bonder: string,
      _principal: string,
      _principalPaid: BigNumberish,
      _payout: BigNumberish,
      _expires: BigNumberish,
      _feo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pendingFor(
      _bonder: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingForIndexes(
      _bonder: string,
      _indexes: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    percentVestedFor(
      _bonder: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    redeem(
      _bonder: string,
      _indexes: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    redeemAll(
      _bonder: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAuthority(
      _newAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFEReward(
      reward: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totalPendingFor(
      _bonder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateIndexesFor(
      _bonder: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    FERs(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    authority(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bonderInfo(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    feReward(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getReward(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    indexesFor(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    newBond(
      _bonder: string,
      _principal: string,
      _principalPaid: BigNumberish,
      _payout: BigNumberish,
      _expires: BigNumberish,
      _feo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pendingFor(
      _bonder: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingForIndexes(
      _bonder: string,
      _indexes: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    percentVestedFor(
      _bonder: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    redeem(
      _bonder: string,
      _indexes: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    redeemAll(
      _bonder: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAuthority(
      _newAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFEReward(
      reward: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totalPendingFor(
      _bonder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateIndexesFor(
      _bonder: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
