name: pnpm CI

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v5

      - name: Install dependencies
        run: pnpm install

      - name: Run test
        run: pnpm run test
